ProjectSurvey/Areas/Administrator/Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using ProjectSurvey.Models;

namespace ProjectSurvey.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class SurveysController : Controller
    {
        private readonly ProjectSurveyContext _context;


        public SurveysController(ProjectSurveyContext context)
        {
            _context = context;
        }

        // GET: Administrator/Surveys
        public async Task<IActionResult> Index()
        { 
           return View(await _context.Survey.ToListAsync());
        }
        //
      

        // GET: Administrator/Surveys/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survey = await _context.Survey
                .FirstOrDefaultAsync(m => m.Id == id);
            if (survey == null)
            {
                return NotFound();
            }

            return View(survey);
        }

        // GET: Administrator/Surveys/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Administrator/Surveys/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Image,SurveyFor,End,CreatedAt,UpdatedAt,Status")] Survey survey)
        {
            if (ModelState.IsValid)
            {
                _context.Add(survey);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(survey);
        }

        // GET: Administrator/Surveys/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survey = await _context.Survey.FindAsync(id);
            if (survey == null)
            {
                return NotFound();
            }
            return View(survey);
        }

        // POST: Administrator/Surveys/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("Id,Title,Description,Image,SurveyFor,End,Status")] Survey survey)
        {           
            if (!_context.Survey.Any(e => e.Id == id))
            {
                return NotFound();
            }
            var existSurvey = await _context.Survey.FindAsync(id);
            if (existSurvey == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    existSurvey.Title = survey.Title;
                    existSurvey.Description = survey.Description;
                    existSurvey.Image = survey.Image;
                    existSurvey.SurveyFor = survey.SurveyFor;
                    existSurvey.Status = survey.Status;
                    existSurvey.End = survey.End;
                    existSurvey.UpdatedAt = DateTime.Now;
                    _context.Update(existSurvey);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(survey);
        }

        // GET: Administrator/Surveys/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survey = await _context.Survey
                .FirstOrDefaultAsync(m => m.Id == id);
            if (survey == null)
            {
                return NotFound();
            }

            return View(survey);
        }

        // POST: Administrator/Surveys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var survey = await _context.Survey.FindAsync(id);
            _context.Survey.Remove(survey);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SurveyExists(int id)
        {
            return _context.Survey.Any(e => e.Id == id);
        }
    }
}

ProjectSurvey/Controllers/PointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectSurvey.Models;

namespace ProjectSurvey.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PointsController : ControllerBase
    {
        private readonly ProjectSurveyContext _context;

        public PointsController(ProjectSurveyContext context)
        {
            _context = context;
        }

        // GET: api/Points
        [HttpGet]
        public IEnumerable<Point> GetPoint()
        {
          return _context.Point;
        }

        //Get api/Points/Users/{id}
        [HttpGet("Users/{id}")]
        public async Task<IActionResult> GetPointByUser([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var point =  _context.Point.Where(q => q.UserId == id && q.Status == PointStatus.Activated);

            if (point.Count() <1 )
            {
                return NotFound();
            }

            return Ok(point);
        }

        // GET: api/Points/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetPoint([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
 
            var point = await _context.Point.FindAsync(id);

            if (point == null)
            {
                return NotFound();
            }

            return Ok(point);
        }

        // PUT: api/Points/5
//        [HttpPut("{id}")]
//        public async Task<IActionResult> PutPoint([FromRoute] int id, [FromBody] Point point)
//        {
//            if (!ModelState.IsValid)
//            {
//                return BadRequest(ModelState);
//            }
//
//            if (id != point.Id)
//            {
//                return BadRequest();
//            }
//
//            _context.Entry(point).State = EntityState.Modified;
//
//            try
//            {
//                await _context.SaveChangesAsync();
//            }
//            catch (DbUpdateConcurrencyException)
//            {
//                if (!PointExists(id))
//                {
//                    return NotFound();
//                }
//                else
//                {
//                    throw;
//                }
//            }
//
//            return NoContent();
//        }

        // POST: api/Points
        [HttpPost]
        public async Task<IActionResult> PostPoint([FromBody] Point point)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _context.Point.Add(point);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetPoint", new { id = point.Id }, point);
        }

        // DELETE: api/Points/5
//        [HttpDelete("{id}")]
//        public async Task<IActionResult> DeletePoint([FromRoute] int id)
//        {
//            if (!ModelState.IsValid)
//            {
//                return BadRequest(ModelState);
//            }
//
//            var point = await _context.Point.FindAsync(id);
//            if (point == null)
//            {
//                return NotFound();
//            }
//
//            _context.Point.Remove(point);
//            await _context.SaveChangesAsync();
//
//            return Ok(point);
//        }

        private bool PointExists(int id)
        {
            return _context.Point.Any(e => e.Id == id);
        }
    }
}

ProjectSurvey/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectSurvey.Models;

namespace ProjectSurvey.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class QuestionsController : ControllerBase
    {
        private readonly ProjectSurveyContext _context;

        public QuestionsController(ProjectSurveyContext context)
        {
            _context = context;
        }

        // GET: api/Questions
        [HttpGet]
        public IEnumerable<Question> GetQuestion()
        {
            return _context.Question.Where(q=> q.Status == QuestionStatus.Activated);
        }
        [HttpGet("Users/{userid}/Surveys/{surveyid}")]
        public IQueryable<Point> GetUserInSurvey(int userid , int surveyid)
        {
            var data =   _context.Point.Where(q=>q.UserId == userid && q.SurveyId ==surveyid);
            
            if (data.Count() < 1  )
            {
               Console.WriteLine("123");
                
            }
            else
            {
               
            }
            return data;
        }
//        return _context.Survey.Where(q => (search != null && (q.Title.Contains(search) && q.Status == SurveyStatus.Activated)


        //
        [HttpGet("Surveys/{id}")]
        [Produces(typeof(Question))]
        public async Task<IActionResult> GetBySurvey(int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var question = _context.Question.Where(q => q.SurveyId == id && (q.Status == QuestionStatus.Activated)).Include(p => p.Survey);

            if (question.Count() < 1  )
            {
                return NotFound("Not found");
            }
            else
            {
                return Ok(question);
            }
        }

        // GET: api/Questions/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetQuestion([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
           
            var question = await _context.Question.FindAsync(id);
          
            if (question == null  && question.Status == QuestionStatus.Deactivated)
            {
                return NotFound();
            }

            return Ok(question);
        }

        // PUT: api/Questions/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutQuestion([FromRoute] int id, [FromBody] Question question)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != question.Id)
            {
                return BadRequest();
            }

            _context.Entry(question).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!QuestionExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Questions
        [HttpPost]
        public async Task<IActionResult> PostQuestion([FromBody] Question question)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _context.Question.Add(question);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetQuestion", new { id = question.Id }, question);
        }

        // DELETE: api/Questions/5
//        [HttpDelete("{id}")]
//        public async Task<IActionResult> DeleteQuestion([FromRoute] int id)
//        {
//            if (!ModelState.IsValid)
//            {
//                return BadRequest(ModelState);
//            }
//
//            var question = await _context.Question.FindAsync(id);
//            if (question == null)
//            {
//                return NotFound();
//            }
//
//            _context.Question.Remove(question);
//            await _context.SaveChangesAsync();
//
//            return Ok(question);
//        }

        private bool QuestionExists(int id)
        {
            return _context.Question.Any(e => e.Id == id);
        }
    }
}

ProjectSurvey/Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectSurvey.Models;

namespace ProjectSurvey.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SurveysController : ControllerBase
    {
        private readonly ProjectSurveyContext _context;

        public SurveysController(ProjectSurveyContext context)
        {
            _context = context;
        }

        // GET: api/Surveys
        [HttpGet]
        public IEnumerable<Survey> GetSurvey([FromQuery]string search = null)
        {
            //            return _context.Survey;
            if (search == null)
            {
                return _context.Survey;
            }
            return _context.Survey.Where(q => (search != null && (q.Title.Contains(search) && q.Status == SurveyStatus.Activated)
                )
            );
        }
        [HttpGet("Role")]
        public IEnumerable<Survey> GetByRole(int id)
        {

            var idUser = AccountID();
            User user = _context.User.SingleOrDefault(i => i.ID == idUser);
            if (user.Role == 2)
            {
                return _context.Survey.Where(q => q.SurveyFor == SurveyFor.Student && (q.Status == SurveyStatus.Activated));
            }
            return _context.Survey.Where(q => q.SurveyFor == SurveyFor.Employee && (q.Status == SurveyStatus.Activated));

        }


        // GET: api/Surveys/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetSurvey([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var survey = await _context.Survey.FindAsync(id);

            if (survey == null)
            {
                return NotFound();
            }

            return Ok(survey);
        }

        // PUT: api/Surveys/5
//        [HttpPut("{id}")]
//        public async Task<IActionResult> PutSurvey([FromRoute] int id, [FromBody] Survey survey)
//        {
//            if (!ModelState.IsValid)
//            {
//                return BadRequest(ModelState);
//            }
//
//            if (id != survey.Id)
//            {
//                return BadRequest();
//            }
//
//            _context.Entry(survey).State = EntityState.Modified;
//
//            try
//            {
//                await _context.SaveChangesAsync();
//            }
//            catch (DbUpdateConcurrencyException)
//            {
//                if (!SurveyExists(id))
//                {
//                    return NotFound();
//                }
//                else
//                {
//                    throw;
//                }
//            }
//
//            return NoContent();
//        }

        // POST: api/Surveys
//        [HttpPost]
//        public async Task<IActionResult> PostSurvey([FromBody] Survey survey)
//        {
//            if (!ModelState.IsValid)
//            {
//                return BadRequest(ModelState);
//            }
//
//            _context.Survey.Add(survey);
//            await _context.SaveChangesAsync();
//
//            return CreatedAtAction("GetSurvey", new { id = survey.Id }, survey);
//        }

        // DELETE: api/Surveys/5
//        [HttpDelete("{id}")]
//        public async Task<IActionResult> DeleteSurvey([FromRoute] int id)
//        {
//            if (!ModelState.IsValid)
//            {
//                return BadRequest(ModelState);
//            }
//
//            var survey = await _context.Survey.FindAsync(id);
//            if (survey == null)
//            {
//                return NotFound();
//            }
//
//            _context.Survey.Remove(survey);
//            await _context.SaveChangesAsync();
//
//            return Ok(survey);
//        }

        private bool SurveyExists(int id)
        {
            return _context.Survey.Any(e => e.Id == id);
        }

        protected int AccountID()
        {
            return int.Parse(this.User.Claims.First(i => i.Type == "UserID").Value);
        }

    }
}

ProjectSurvey/Areas/Administrator/Views/Surveys/Create.cshtml
@model ProjectSurvey.Models.Survey

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Survey</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SurveyFor" class="control-label"></label>
                <select       asp-items="Html.GetEnumSelectList<SurveyFor>()"  class="control-label"></select>
                <span asp-validation-for="SurveyFor" class="text-danger"></span>
               
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="Html.GetEnumSelectList<SurveyStatus>()"  class="control-label"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@* @section Scripts { *@
@*     @{await Html.RenderPartialAsync("_ValidationScriptsPartial");} *@
@* } *@

ProjectSurvey/Areas/Administrator/Views/Surveys/Delete.cshtml
@model ProjectSurvey.Models.Survey

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Survey</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SurveyFor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SurveyFor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectSurvey/Areas/Administrator/Views/Surveys/Details.cshtml
@model ProjectSurvey.Models.Survey

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Survey</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SurveyFor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SurveyFor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjectSurvey/Areas/Administrator/Views/Surveys/Edit.cshtml
@model ProjectSurvey.Models.Survey

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Survey</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SurveyFor" class="control-label"></label>

                <select  asp-for="SurveyFor" asp-items="Html.GetEnumSelectList<SurveyFor>()" class="control-label"></select>
                <span asp-validation-for="SurveyFor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select  asp-for="Status" asp-items="Html.GetEnumSelectList<SurveyStatus>()" class="control-label"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@* @section Scripts { *@
@*     @{await Html.RenderPartialAsync("_ValidationScriptsPartial");} *@
@* } *@

ProjectSurvey/Areas/Administrator/Views/Surveys/Index.cshtml
@model IEnumerable<ProjectSurvey.Models.Survey>



@{
    ViewData["Title"] = "Index";
}

<h2>Survey</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
	    <th>
		    @Html.DisplayNameFor(model => model.Id)
	    </th>
	    <th>
		    @Html.DisplayNameFor(model => model.Title)
	    </th>
	    <th>
		    @Html.DisplayNameFor(model => model.Description)
	    </th>
	    <th>
		    @Html.DisplayNameFor(model => model.Image)
	    </th>
	    <th>
		    @Html.DisplayNameFor(model => model.SurveyFor)
	    </th>
	    <th>
		    @Html.DisplayNameFor(model => model.End)
	    </th>
	    <th>
		    @Html.DisplayNameFor(model => model.Status)
	    </th>
	    <th></th>
    </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
	        <tr>
				<td>
					@Html.DisplayFor(modelItem => item.Id)
				</td>
		        <td>
			        @Html.DisplayFor(modelItem => item.Title)
		        </td>
		        <td>
			        @Html.DisplayFor(modelItem => item.Description)
		        </td>
		        <td>
			        @Html.DisplayFor(modelItem => item.Image)
		        </td>
		        <td>
			        @Html.DisplayFor(modelItem => item.SurveyFor)
		        </td>
		        <td>
			        @Html.DisplayFor(modelItem => item.End)
		        </td>
		        <td>
			        @Html.DisplayFor(modelItem => item.Status)
		        </td>
		        <td>
			        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
			        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
			        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
			        <a asp-controller="Points" asp-action="GetBySurvey"asp-route-id="@item.Id"  >All Users Answered </a> |
			        <a asp-controller="Questions" asp-action="GetBySurveyId"asp-route-id="@item.Id"  >All Questions </a>




		        </td>
	        </tr>
        }
    </tbody>
</table>